/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ImageInserter
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/file_modal.ts
var import_obsidian2 = require("obsidian");

// src/file_embedder.ts
var import_obsidian = require("obsidian");
var FileEmbedder = class {
  constructor(app, attachmentsFolder) {
    this.app = app;
    this.attachmentsFolder = attachmentsFolder;
  }
  embedLinkFor(file) {
    return "![[" + file.path + "]]\n";
  }
  async copyFileToAttachmentsDir(file) {
    if (!this.app.vault.getAbstractFileByPath(this.attachmentsFolder)) {
      await this.app.vault.createFolder(this.attachmentsFolder);
    }
    const destination = this.getAvailableDestination(file.name);
    const buffer = await file.arrayBuffer();
    return await this.app.vault.createBinary(destination, buffer);
  }
  // Return a unique path for the provided filename to avoid overwriting attachments
  getAvailableDestination(filename) {
    const extensionStart = filename.lastIndexOf(".");
    const basename = extensionStart > 0 ? filename.slice(0, extensionStart) : filename;
    const extension = extensionStart > 0 ? filename.slice(extensionStart) : "";
    let index = 0;
    while (true) {
      const candidateName = index === 0 ? filename : `${basename} (${index})${extension}`;
      const candidatePath = (0, import_obsidian.normalizePath)(`${this.attachmentsFolder}/${candidateName}`);
      if (!this.app.vault.getAbstractFileByPath(candidatePath)) {
        return candidatePath;
      }
      index++;
    }
  }
};

// src/file_modal.ts
var FileModal = class extends import_obsidian2.Modal {
  constructor(app) {
    super(app);
  }
  onOpen() {
    const { contentEl } = this;
    const input = contentEl.createEl("input", {
      type: "file",
      attr: { accept: "image/*", multiple: true }
    });
    input.addEventListener("cancel", () => {
      new import_obsidian2.Notice("Canceled adding images");
      this.close();
    });
    input.addEventListener("change", async () => {
      this.close();
      const attachmentsDest = this.getAttachmentsDestination();
      const fileEmbedder = new FileEmbedder(this.app, attachmentsDest);
      const fileList = Array.from(input.files || []);
      let failedCount = 0;
      for (const file of fileList) {
        try {
          const copiedFile = await fileEmbedder.copyFileToAttachmentsDir(file);
          const embedLinkToFile = fileEmbedder.embedLinkFor(copiedFile);
          this.addText(embedLinkToFile);
        } catch (error) {
          failedCount++;
          console.error(error);
        }
      }
      if (failedCount > 0) {
        new import_obsidian2.Notice(
          `Added ${fileList.length - failedCount} images; ${failedCount} failed to be inserted`
        );
      } else {
        new import_obsidian2.Notice(`Added ${fileList.length} images`);
      }
    });
    input.click();
  }
  getAttachmentsDestination() {
    var _a, _b, _c;
    const vault = this.app.vault;
    const attachmentFolder = (_a = vault.getConfig("attachmentFolderPath")) != null ? _a : "/";
    if (attachmentFolder.startsWith("./")) {
      const activeFile = this.app.workspace.getActiveFile();
      const activeFolderPath = (_c = (_b = activeFile == null ? void 0 : activeFile.parent) == null ? void 0 : _b.path) != null ? _c : "";
      const relativeAttachmentFolder = attachmentFolder.slice(2);
      return (0, import_obsidian2.normalizePath)(`${activeFolderPath}/${relativeAttachmentFolder}`);
    }
    return attachmentFolder;
  }
  addText(text) {
    const view = this.app.workspace.getActiveViewOfType(import_obsidian2.MarkdownView);
    if (view) {
      view.editor.replaceSelection(text);
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// main.ts
var ImageInserter = class extends import_obsidian3.Plugin {
  async onload() {
    this.addCommand({
      id: "image-insert",
      name: "Insert image(s)",
      callback: () => {
        new FileModal(this.app).open();
      }
    });
  }
};

/* nosourcemap */